### ISSUE TITLE
[showstopper] TypeError: Cannot read property 'transformedQuery' of undefined

### ISSUE THREAD

**Issue by martinhbramwell** [apollographql/GitHunt-API#140]
I am unable to do anything with this repo.  When I open the URL [http://localhost:3010/graphiql](http://localhost:3010/graphiql), then the immediate result is...

    TypeError: Cannot read property 'transformedQuery' of undefined
      at /home/you/projects/githunt/GitHunt-API/node_modules/extractgql/src/server/serverUtil.ts:91:52
      at Layer.handle [as handle_request] (/home/you/projects/githunt/GitHunt-API/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/home/you/projects/githunt/GitHunt-API/node_modules/express/lib/router/index.js:312:13)
      at /home/you/projects/githunt/GitHunt-API/node_modules/express/lib/router/index.js:280:7
      at Function.process_params (/home/you/projects/githunt/GitHunt-API/node_modules/express/lib/router/index.js:330:12)
      at next (/home/you/projects/githunt/GitHunt-API/node_modules/express/lib/router/index.js:271:10)
      at /home/you/projects/githunt/GitHunt-API/node_modules/body-parser/lib/read.js:129:5
      at invokeCallback (/home/you/projects/githunt/GitHunt-API/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
      at done (/home/you/projects/githunt/GitHunt-API/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
      at IncomingMessage.onEnd (/home/you/projects/githunt/GitHunt-API/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
      at emitNone (events.js:67:13)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:923:12)
      at nextTickCallbackWith2Args (node.js:458:9)
      at process._tickDomainCallback (node.js:413:17)

I have posted my complete CLI log of cloning, installing, building and running as a gist : [martinhbramwell/BuildAndRun.log :: GitHunt-API crash](https://gist.github.com/martinhbramwell/cecd31088f327e75f81907dd131a3b3e)

My environment is : 

    you@hab4metdev:~/projects/githunt/GitHunt-API$ lsb_release -a
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.1 LTS
    Release:	16.04
    Codename:	xenial
    you@hab4metdev:~/projects/githunt/GitHunt-API$ node --version
    v4.7.2
    you@hab4metdev:~/projects/githunt/GitHunt-API$ npm --version
    2.15.11
    you@hab4metdev:~/projects/githunt/GitHunt-API$

**Comment by alexthewilde** [comment]
Same issue here.

**Comment by glmdevops** [comment]
Samesies, thx!

**Comment by delkopiso** [comment]
Same here

**Comment by pward123** [comment]
From https://github.com/apollostack/GitHunt-API/issues/140, setting persistedQueries to false in /api/config.js fixed the issue for me

**Comment by taniadaniela** [comment]
@pward123 that setting cause an error with the githunt-react when you try to access the react app.

**Comment by yourse1f-yourorg** [comment]
Please accept my apologies for opening a duplicate issue.

**Comment by Poincare** [comment]
We should probably put this in the docs, but unless you set persistedQueries to false, you can't use GraphiQL.

**Comment by helfer** [comment]
@Poincare in that case we should consider allowing non-whitelisted queries as well by default, or turning off persistedQueries by default. This seems to be a problem that a lot of people run into...

**Comment by helfer** [comment]
Should be fixed now. Please reopen if it's not!
