### ISSUE TITLE
basic.js (accepts a query) test fails out of the box

### ISSUE THREAD

**Issue by gihrig** [apollographql/GitHunt-API#193]
**Expected:**
All tests provided with the project pass on a fresh install.

**Actual:**
api/github/connector.test.js PASS
__tests__/basic.js FAIL

**Details:**
![image](https://cloud.githubusercontent.com/assets/1481063/23982891/b974031e-09cd-11e7-94d2-53a1fd3c8e4b.png)
![image](https://cloud.githubusercontent.com/assets/1481063/23982898/d383e314-09cd-11e7-8ca0-7b9e7d99c460.png)
![image](https://cloud.githubusercontent.com/assets/1481063/23982911/eb012b00-09cd-11e7-8779-5b1d14aa2f59.png)

**To reproduce:**
1. Follow all seven steps in the README [Running the server](https://github.com/apollographql/GitHunt-API#running-the-server) section. 
 - The server functions as described.
 - The default GraphiQL query returns meaningful results.
2. Stop the server.
3. execute `npm test`.

**Comment by stubailo** [comment]
did you run the migrations for the test database with `npm run test:setup`?

**Comment by gihrig** [comment]
Yes, completed all 7 steps as listed. 

Querying the server through GraphiQL against the 'feed' query works as expected. 'feed' is the query mentioned in the failing test log.

**Comment by gihrig** [comment]
> did you run the migrations for the test database with npm run test:setup?

Sorry, I responded without fully groking your question 😊 

But there is no `test:setup` in package.json scripts...

**Comment by stubailo** [comment]
Hmm, you shouldn't need it installed! I'm not sure why this is happening. Let me try to run locally.

**Comment by gihrig** [comment]
Please wait on that local run, I think I have a local config error. Stand by...

**Comment by gihrig** [comment]
OK, so I had made some mods to the copy of GitHunt-API I was testing on....

 - Working with a fresh clone (now cloned into gh-api folder).
 - Added `npm run test:setup` to the end of step three in README [Running the server](https://github.com/apollographql/GitHunt-API#running-the-server).
 - Server runs as expected, `feed` query produces expected result in GraphiQL.
 - Still getting a failure in `npm test`, but it's now a different error.
![image](https://cloud.githubusercontent.com/assets/1481063/23986014/473e6d86-09df-11e7-8627-82be3b479799.png)
![image](https://cloud.githubusercontent.com/assets/1481063/23986049/6acb43be-09df-11e7-927b-db6a62b06ac4.png)

**Comment by calebmer** [comment]
@gihrig we can’t see the entire error in the second image. Could you show us the error message that you get?

**Comment by gihrig** [comment]
@calebmer 

Looking closer I'm wondering if there is actually nothing really wrong. The snapshot just needs to be updated to include `client_id` and `client_secret`?

Indeed, when I update the snapshot, the tests all pass. It just looks bad because of the "error",  actually a warning from bulebird, as listed in the top image.

```bash
    console.warn node_modules/bluebird/js/release/debuggability.js:870
      Unhandled rejection TypeError: setTimeout(...).unref is not a function
          at /Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/connect-session-knex/index.js:99:53
          at PassThroughHandlerContext.finallyHandler (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/finally.js:56:23)
          at PassThroughHandlerContext.tryCatcher (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/util.js:16:23)
          at Promise._settlePromiseFromHandler (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:512:31)
          at Promise._settlePromise (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:569:18)
          at Promise._settlePromise0 (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:614:10)
          at Promise._settlePromises (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:693:18)
          at Async.Object.<anonymous>.Async._drainQueue (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:133:16)
          at Async.Object.<anonymous>.Async._drainQueues (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:143:10)
          at Immediate.Async.drainQueues (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:17:14)
          at runCallback (timers.js:666:20)
          at tryOnImmediate (timers.js:639:5)
          at processImmediate [as _immediateCallback] (timers.js:611:5)
```

In case you are interested, feel free to ignore if not. The remaining stack trace at the end of the (long) test result screen is:
```bash
  at _callee$ (__tests__/basic.js:78:26)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at step (__tests__/basic.js:4:317)
      at __tests__/basic.js:4:477
```

In case that is not what you need, here's the whole screen (with client id and secret obfuscated):
```bash
Dev-Mac-WS:gh-api glen$ npm test

> githunt-api@1.0.0 test /Users/glen/Documents/JavaScript/Research/GraphQL/gh-api
> jest && npm run lint

 FAIL  __tests__/basic.js (6.222s)
  ● Console

    console.warn node_modules/subscriptions-transport-ws/node_modules/graphql-tag/printer.js:3
      Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
      See https://github.com/apollographql/graphql-tag/issues/54 for more information.
    console.log api/server.js:132
      API Server is now running on http://localhost:6789
    console.warn node_modules/bluebird/js/release/debuggability.js:870
      Unhandled rejection TypeError: setTimeout(...).unref is not a function
          at /Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/connect-session-knex/index.js:99:53
          at PassThroughHandlerContext.finallyHandler (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/finally.js:56:23)
          at PassThroughHandlerContext.tryCatcher (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/util.js:16:23)
          at Promise._settlePromiseFromHandler (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:512:31)
          at Promise._settlePromise (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:569:18)
          at Promise._settlePromise0 (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:614:10)
          at Promise._settlePromises (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/promise.js:693:18)
          at Async.Object.<anonymous>.Async._drainQueue (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:133:16)
          at Async.Object.<anonymous>.Async._drainQueues (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:143:10)
          at Immediate.Async.drainQueues (/Users/glen/Documents/JavaScript/Research/GraphQL/gh-api/node_modules/bluebird/js/release/async.js:17:14)
          at runCallback (timers.js:666:20)
          at tryOnImmediate (timers.js:639:5)
          at processImmediate [as _immediateCallback] (timers.js:611:5)
      

  ● accepts a query

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
     Object {
       "data": Object {
         "feed": Array [
    -      Object {
    -        "postedBy": Object {
    -          "login": "stubailo",
    +      null,
    +      null,
    +      null,
    +      null,
    +      null,
    +    ],
    +  },
    +  "errors": Array [
    +    Object {
    +      "locations": Array [
    +        Object {
    +          "column": 9,
    +          "line": 4,
             },
    -        "repository": Object {
    -          "name": "apollo-client",
    -          "owner": Object {
    -            "login": "apollographql",
    -          },
    +      ],
    +      "message": "expect(received).toEqual(expected)
    +
    +Expected value to equal:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/apollographql/apollo-client"}
    +Received:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "qs": {"client_id": "xxxxxxxxxxxxxxxxxxxx", "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/apollographql/apollo-client"}
    +
    +Difference:
    +
    +- Expected
    ++ Received
    +
    + Object {
    +   "headers": Object {
    +     "user-agent": "GitHunt",
    +   },
    +   "json": true,
    ++  "qs": Object {
    ++    "client_id": "xxxxxxxxxxxxxxxxxxxx",
    ++    "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    ++  },
    +   "resolveWithFullResponse": true,
    +   "uri": "https://api.github.com/repos/apollographql/apollo-client",
    + }",
    +      "path": Array [
    +        "feed",
    +        0,
    +        "repository",
    +      ],
    +    },
    +    Object {
    +      "locations": Array [
    +        Object {
    +          "column": 9,
    +          "line": 4,
             },
    -      },
    -      Object {
    -        "postedBy": Object {
    -          "login": "helfer",
    +      ],
    +      "message": "expect(received).toEqual(expected)
    +
    +Expected value to equal:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/apollographql/graphql-server"}
    +Received:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "qs": {"client_id": "xxxxxxxxxxxxxxxxxxxx", "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/apollographql/graphql-server"}
    +
    +Difference:
    +
    +- Expected
    ++ Received
    +
    + Object {
    +   "headers": Object {
    +     "user-agent": "GitHunt",
    +   },
    +   "json": true,
    ++  "qs": Object {
    ++    "client_id": "xxxxxxxxxxxxxxxxxxxx",
    ++    "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    ++  },
    +   "resolveWithFullResponse": true,
    +   "uri": "https://api.github.com/repos/apollographql/graphql-server",
    + }",
    +      "path": Array [
    +        "feed",
    +        1,
    +        "repository",
    +      ],
    +    },
    +    Object {
    +      "locations": Array [
    +        Object {
    +          "column": 9,
    +          "line": 4,
             },
    -        "repository": Object {
    -          "name": "graphql-server",
    -          "owner": Object {
    -            "login": "apollographql",
    -          },
    +      ],
    +      "message": "expect(received).toEqual(expected)
    +
    +Expected value to equal:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/meteor/meteor"}
    +Received:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "qs": {"client_id": "xxxxxxxxxxxxxxxxxxxx", "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/meteor/meteor"}
    +
    +Difference:
    +
    +- Expected
    ++ Received
    +
    + Object {
    +   "headers": Object {
    +     "user-agent": "GitHunt",
    +   },
    +   "json": true,
    ++  "qs": Object {
    ++    "client_id": "xxxxxxxxxxxxxxxxxxxx",
    ++    "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    ++  },
    +   "resolveWithFullResponse": true,
    +   "uri": "https://api.github.com/repos/meteor/meteor",
    + }",
    +      "path": Array [
    +        "feed",
    +        2,
    +        "repository",
    +      ],
    +    },
    +    Object {
    +      "locations": Array [
    +        Object {
    +          "column": 9,
    +          "line": 4,
             },
    -      },
    -      Object {
    -        "postedBy": Object {
    -          "login": "tmeasday",
    +      ],
    +      "message": "expect(received).toEqual(expected)
    +
    +Expected value to equal:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/twbs/bootstrap"}
    +Received:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "qs": {"client_id": "xxxxxxxxxxxxxxxxxxxx", "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "resolveWithFullResponse": true, "uri": "https://api.github.com/repos/twbs/bootstrap"}
    +
    +Difference:
    +
    +- Expected
    ++ Received
    +
    + Object {
    +   "headers": Object {
    +     "user-agent": "GitHunt",
    +   },
    +   "json": true,
    ++  "qs": Object {
    ++    "client_id": "xxxxxxxxxxxxxxxxxxxx",
    ++    "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    ++  },
    +   "resolveWithFullResponse": true,
    +   "uri": "https://api.github.com/repos/twbs/bootstrap",
    + }",
    +      "path": Array [
    +        "feed",
    +        3,
    +        "repository",
    +      ],
    +    },
    +    Object {
    +      "locations": Array [
    +        Object {
    +          "column": 9,
    +          "line": 9,
             },
    -        "repository": Object {
    -          "name": "meteor",
    -          "owner": Object {
    -            "login": "meteor",
    -          },
    -        },
    -      },
    -      Object {
    -        "postedBy": Object {
    -          "login": "Slava",
    -        },
    -        "repository": Object {
    -          "name": "bootstrap",
    -          "owner": Object {
    -            "login": "twbs",
    -          },
    -        },
    -      },
    -      Object {
    -        "postedBy": Object {
    -          "login": "Slava",
    -        },
    -        "repository": Object {
    -          "name": "d3",
    -          "owner": Object {
    -            "login": "d3",
    -          },
    -        },
    -      },
    -    ],
    -  },
    +      ],
    +      "message": "expect(received).toEqual(expected)
    +
    +Expected value to equal:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "resolveWithFullResponse": true, "uri": "https://api.github.com/users/Slava"}
    +Received:
    +  {"headers": {"user-agent": "GitHunt"}, "json": true, "qs": {"client_id": "xxxxxxxxxxxxxxxxxxxx", "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"}, "resolveWithFullResponse": true, "uri": "https://api.github.com/users/Slava"}
    +
    +Difference:
    +
    +- Expected
    ++ Received
    +
    + Object {
    +   "headers": Object {
    +     "user-agent": "GitHunt",
    +   },
    +   "json": true,
    ++  "qs": Object {
    ++    "client_id": "xxxxxxxxxxxxxxxxxxxx",
    ++    "client_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    ++  },
    +   "resolveWithFullResponse": true,
    +   "uri": "https://api.github.com/users/Slava",
    + }",
    +      "path": Array [
    +        "feed",
    +        4,
    +        "postedBy",
    +      ],
    +    },
    +  ],
     }
      
      at _callee$ (__tests__/basic.js:78:26)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at step (__tests__/basic.js:4:317)
      at __tests__/basic.js:4:477

 PASS  api/github/connector.test.js

Snapshot Summary
 › 1 snapshot test failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   1 failed, 1 total
Time:        7.942s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
Dev-Mac-WS:gh-api glen$ 
```
